version: '3'
services:
  user_service_db:
    image: mysql:latest
    container_name: user_service_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456a@
      - MYSQL_DATABASE=user_service
    volumes:
      - D:/LMS-Microservice/database/user_service:/var/lib/mysql