spring.application.name=chat-service
server.port=8084

spring.config.import=configserver:http://localhost:8888

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=chat_keyspace
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.username=cassandra
spring.cassandra.password=cassandra
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
